### ISSUE TITLE
Checkout out The GraphQuilt Orchestrator

### ISSUE THREAD

**Issue by ashpak-shaikh** [friatech/lilo#17]
Hello, creating an issue to invite you to check out the GraphQL Orchestrator Library from Graph Quilt (licensed to Intuit Inc.) We started with braid as well but built this library 3 years back due to inactivity.  

https://github.com/graph-quilt/graphql-orchestrator-java

**Comment by firatkucuk** [comment]
I've mentioned, your project in README file. Thanks for the report.
