### ISSUE TITLE
Lilo doesn't allow instrumentation to be set in graphql builder

### ISSUE THREAD

**Issue by ShibyNiju** [friatech/lilo#20]
Graphql provides instrumentation as well as exception handlers to be configured. But Lilo doesn't provide a provision to do this.

**Comment by firatkucuk** [comment]
That's also a good feature request. I am gonna take a look at that one as well.

**Comment by firatkucuk** [comment]
The new `23.4.1` Release supports instrumentation. Feel free to reopen the issue if you encounter any other problems.

**Comment by ShibyNiju** [comment]
I will surely try this out and thanks for taking this up so fast :)
